language: ruby
bundler_args: --without development

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.2.0
  - jruby-19mode

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
